env = Environment()

env['APP_TARGET'] = 'Prothesis2'
#env['APP_SOURCES'] = ['Prothesis2.cpp', 'Capture1394PParams.cpp', 'CaptureSource.cpp', 'FluidParticles.cpp']
env['APP_SOURCES'] = ['Prothesis2.cpp', 'CaptureSource.cpp', 'FluidParticles.cpp']
env['DEBUG'] = 0

env = SConscript('../blocks/msaFluid/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/Cinder-OpenCV/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/Cinder-NI/scons/SConscript', exports = 'env')
SConscript('../../../../blocks/MndlKit/scons/SConscript', exports = 'env')
#SConscript('../../../../blocks/Cinder-Capture1394/scons/SConscript', exports = 'env')
SConscript('../../../../scons/SConscript', exports = 'env')

