env = Environment()

env['APP_TARGET'] = 'Prothesis2'
env['APP_SOURCES'] = ['Prothesis2App.cpp']
env['APP_SOURCES'] += ['SmokeEffect.cpp', 'FluidParticles.cpp']
env['DEBUG'] = 0

env = SConscript('../../../../blocks/MndlKit/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/Cinder-NI/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/Cinder-OpenCV/scons/SConscript', exports = 'env')
env = SConscript('../blocks/msaFluid/scons/SConscript', exports = 'env')

SConscript('../../../../scons/SConscript', exports = 'env')

