env = Environment()

env['APP_TARGET'] = 'SkelMeshApp'
env['APP_SOURCES'] = ['SkelMeshApp.cpp']
env['RESOURCES'] = ['shaders/*']

env = SConscript('../../../../blocks/Cinder-NI/scons/SConscript', exports = 'env')
env = SConscript('../../../../blocks/MndlKit/scons/SConscript', exports = 'env')

SConscript('../../../../scons/SConscript', exports = 'env')
