env = Environment()

env['APP_TARGET'] = 'SkelMeshApp'
env['APP_SOURCES'] = ['SkelMeshApp.cpp']

# Cinder-NI
env = SConscript('../../../../blocks/Cinder-NI/scons/SConscript', exports = 'env')

SConscript('../../../../scons/SConscript', exports = 'env')
